if(NOT HAVE_XINE AND PKG_CONFIG_FOUND)
  pkg_check_modules(XINE libxine QUIET)
  if(XINE_FOUND)
    set(HAVE_XINE TRUE)
  endif()
endif()

if(HAVE_XINE)
  add_library(ocv::3rdparty::xine INTERFACE IMPORTED)
  set_target_properties(ocv::3rdparty::xine PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${XINE_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${XINE_LIBRARIES}"
    INTERFACE_COMPILE_DEFINITIONS "HAVE_XINE")
endif()

set(HAVE_XINE ${HAVE_XINE} PARENT_SCOPE)
